spring.application.name=AdditivesManager


spring.datasource.url=jdbc:postgresql://localhost:5432/additives_manager
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=199815ru

# Диалект Hibernate (PostgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Отключаем DDL (чтобы не конфликтовал с Flyway)
spring.jpa.hibernate.ddl-auto=none

# Включить Flyway
spring.flyway.enabled=true

# Путь к миграциям (по умолчанию db/migration)
spring.flyway.locations=classpath:db/migration

# Очищать БД перед миграцией (только для dev!)
spring.flyway.clean-disabled=false

# Версионирование таблицы
spring.flyway.table=flyway_schema_history

# Кодировка
spring.flyway.encoding=UTF-8